select * from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select [房间类型] from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select distinct [房间类型] from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select distinct [房间类型] from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [房间类型];
select distinct [房间类型] as RoomTypeName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [房间类型];
select distinct [房间类型] as RoomTypeName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by RoomTypeName;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_RoomType];
select distinct [出租方式] as RentWay from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [出租方式];
select distinct [出租方式] as RentWayName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by RentWayName;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_RentWay];
select distinct [装修类型] as DecorationTypeName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [装修类型];
select distinct [装修类型] as DecorationTypeName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by DecorationTypeName;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_DecorationType];
select distinct [楼层] from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [楼层];
select distinct [楼层] as FloorSectionName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [楼层];
select distinct [楼层] as FloorSectionName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by FloorSectionName;
select distinct [楼层] as FloorSectionName ,left([楼层],charindex('/',[楼层])-1) as Minimum ,right([楼层],len([楼层])-charindex('/',[楼层])) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by FloorSectionName;
select distinct [楼层] as FloorSectionName ,CAST(left([楼层],charindex('/',[楼层])-1) as int ) as Minimum ,CAST(substring([楼层],charindex('/',[楼层])+1,len([楼层])-charindex('/',[楼层])-1) AS int) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by FloorSectionName;
select distinct [楼层] as FloorSectionName ,CONVERT(int,left([楼层],charindex('/',[楼层])-1)) as Minimum ,CONVERT(int,substring([楼层],charindex('/',[楼层])+1,len([楼层])-charindex('/',[楼层])-1)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by FloorSectionName;
select max(CAST(substring([楼层],charindex('/',[楼层])+1,len([楼层])-charindex('/',[楼层])-1) as int)) as MostMaximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(CAST(left([楼层],charindex('/',[楼层])-1) as int )) as MostMinimum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select max(CONVERT(int,substring([楼层],charindex('/',[楼层])+1,len([楼层])-charindex('/',[楼层])-1))) as MostMaximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(CONVERT(int,left([楼层],charindex('/',[楼层])-1))) as MostMinimum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_FloorSection];
truncate table [ZFBI_Study_DW].[dbo].[DW_Dim_FloorSection];
delete from [ZFBI_Study_DW].[dbo].[DW_Dim_FloorSection];
dbcc checkident('[ZFBI_Study_DW].[dbo].[DW_Dim_FloorSection]',reseed,0);
select distinct [区县] as CountyCity,[区域] as Region,[位置道路] as Location from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [区域];
select distinct [区县] as CountyCity,[区域] as Region,[位置道路] as Location from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by Region;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_Region];
select distinct [是否地铁]  from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [是否地铁];
select distinct [是否地铁] as IsUnderGroundName from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by IsUnderGroundName;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_IsUnderGround];
select distinct [月租]  from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by [月租];
select max(CAST([月租] as int)) as Maximum  from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(CAST([月租] as int)) as Minimum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select max(CONVERT(int,[月租])) as Maximum  from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(CONVERT(int,[月租])) as Minimum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select max(CONVERT(int,[月租],10)) as Maximum  from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(CONVERT(int,[月租],10)) as Minimum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(cast([月租] as int)) as Minimum,max(cast([月租] as int)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(convert(int,[月租])) as Minimum,max(convert(int,[月租])) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select min(convert(int,[月租],10)) as Minimum,max(convert(int,[月租],10)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];
select cast(min(cast([月租] as int)) as varchar(14))+'-'+cast(max(cast([月租] as int))as varchar(15)) as RentSectionName,min(cast([月租] as int)) as Minimum,max(cast([月租] as int)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by RentSectionName;
select cast(min(convert(int,[月租])) as varchar(14))+'-'+cast(max(convert(int,[月租]))as varchar(15)) as RentSectionName,min(cast([月租] as int)) as Minimum,max(cast([月租] as int)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by RentSectionName;
select cast(min(convert(int,[月租],10)) as varchar(14))+'-'+cast(max(convert(int,[月租],10))as varchar(15)) as RentSectionName,min(cast([月租] as int)) as Minimum,max(cast([月租] as int)) as Maximum from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ] order by RentSectionName;
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_DW].[dbo].[DW_Dim_RentSection];
truncate table [ZFBI_Study_DW].[dbo].[DW_Dim_RentSection];
delete from [ZFBI_Study_DW].[dbo].[DW_Dim_RentSection];
dbcc checkident('[ZFBI_Study_DW].[dbo].[DW_Dim_RentSection]',reseed,0);
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_Fact_ZF_AllDate_GZ];
select count(0) from [DESKTOP-NNRODTU].[ZFBI_Study_ODS].[dbo].[ODS_ZF_AllDate_GZ];